#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

#------------------------------------------------------------------------------

if [[ "$WM_PROJECT_DIR" == "OpenFOAM" ]]; then
    echo
    echo "Cleaning functionObjects"
    echo

    wclean lib field
fi

#------------------------------------------------------------------------------
