#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

#------------------------------------------------------------------------------

echo
echo "Cleaning functionObjects"
echo

if [[ "$WM_PROJECT_DIR" == "OpenFOAM" ]]; then
    wclean lib field
fi

#------------------------------------------------------------------------------
