#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ "$PWD" != "$CUSTOM_PROJECT_DIR" ]
then
    echo "Error: Current directory is not \$CUSTOM_PROJECT_DIR"
    echo "    The environment variable are not consistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
fi

# build custom libraries and applications
src/Allwmake
#applications/Allwmake

# ----------------------------------------------------------------- end-of-file
