#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1
else
    allowed_ver=("4.1" "9" "v2312")
    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
        echo "Unsupported OpenFOAM version sourced!"
    fi
fi

# Clean libraries
(cd src && ./Allwclean)

# Clean applications
(cd applications && ./Allwclean)

#------------------------------------------------------------------------------
