#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

echo
echo "Cleaning applications"
echo

# Select projects that, currently, are only 
# available in either platform.
if [ "$WM_PROJECT" = "foam" ]
then
    wclean all utilities/postProcessing/velocityField
    wclean all utilities/postProcessing/wall
else
    wclean all utilities/mesh
fi

#------------------------------------------------------------------------------
