#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$PWD" != "${CUSTOM_PROJECT_DIR}/applications" ]; then
    echo "Error: Current directory in not \$CUSTOM_PROJECT_DIR/applications"
    echo "    The environment variable are not consistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
fi

#set -x

# Select projects that, currently, are only 
# available in either platform.
if [ "$WM_PROJECT" = "foam" ]
then
    wmake all utilities/postProcessing/velocityField
    wmake all utilities/postProcessing/wall
else
    wmake all utilities/mesh
fi

# ----------------------------------------------------------------- end-of-file
