#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
#set -x

# Parse arguments for library compilation
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then
    . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
fi

if [ "$WM_PROJECT" = "foam" ]
then
    #if [ ! -f Make/files ]
    #then
    #    echo "Linking Make/files.foamextend to Make/files"
    #    (cd Make && ln -s files.foamextend files)
    #elif [ $(readlink Make/files) != "files.foamextend" ]
    #then
    #    echo "Updating Make/files link to Make/files.foamextend"
    #    (cd Make && ln -sf files.foamextend files)
    #fi

    wmake libso incompressible

else
    echo "Skipping transportModels library as models already"
    echo "included in OpenFOAM core library."
    exit 0
fi

# ----------------------------------------------------------------- end-of-file
