#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

echo
echo "Cleaning src"
echo

wclean lib finiteVolume
wclean lib functionObjects
wclean lib solids4FoamModels

#------------------------------------------------------------------------------
