#!/bin/bash
cd "${0%/*}" || exit  # Run from this directory

echo
echo "Cleaning src"
echo

wclean lib finiteVolume

if [[ -d "$SOLIDS4FOAM_ROOT" ]]; then
    echo "Cleaning solids4FoamModels"
    wclean lib solids4FoamModels
fi

functionObjects/Allwclean

#------------------------------------------------------------------------------
